name: Create Pull Request
on:
  release:
    types:
      - published

jobs:
  update_fork:
    name: Create Contrib Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push contrib branch
        env:
          CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
          CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
          CI_USER_USERNAME: ${{ secrets.CI_USER_USERNAME }}
          CI_USER_ACCESS_TOKEN: ${{ secrets.CI_USER_ACCESS_TOKEN }}
        run: |
          git config --global user.email "CI_USER_EMAIL"
          git config --global user.name  "CI_USER_NAME"
          ./scripts/push-contrib-branch.sh
